name: 构建部署BLOG
on: push

permissions:
  contents: write

jobs:
  build:
    name: 构建
    runs-on: ubuntu-latest
    steps: 
    - name: 拉取代码
      uses: actions/checkout@v4

    - name: 安装依赖
      run: 
        npm i

    - name: 打包
      run:
        npm run build
        cd ..

    - name: 部署到github个人主页
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build

    - name: 创建并使用docker远程上下文
      env: 
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      shell: bash
      run: | 
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        docker context create remote --docker "host=ssh://operation@$SSH_HOST"
        docker context use remote

    - name: 停止历史容器并删除镜像
      run: |
        docker ps
        docker stop blog-v1 || true
        docker rm blog-v1 || true
        docker rmi blog || true
    
    - name: 构建镜像并运行容器
      run: |
        docker build -t blog .
        docker run -d -p 1234:80 --name blog-v1  blog
