name: 构建部署BLOG
on: push

permissions:
  contents: write

jobs:
  build:
    name: 构建
    runs-on: ubuntu-latest
    steps: 
    - name: 拉取代码
      uses: actions/checkout@v4

    - name: 安装依赖
      run: 
        npm i

    - name: 打包
      run:
        npm run build
        cd ..

    - name: 部署到github个人主页
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build

    - name: 部署到服务器docker
      env: 
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: | 
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no "operation@$SSH_HOST" << EOF
          docker ps
          docker stop blog-v1 || true
          docker rm blog-v1 || true
          docker rmi blog || true
          docker build -t blog .
          docker run -d -p 1234:80 --name blog-v1  blog
        EOF