name: 构建部署BLOG
on: push

permissions:
  contents: write

jobs:
  build:
    name: 构建
    runs-on: ubuntu-latest
    steps: 
    - name: 拉取代码
      uses: actions/checkout@v4

    - name: 安装依赖
      run: 
        npm i

    - name: 打包
      run:
        npm run build
        cd ..

    - name: 部署
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
